### PR TITLE
Features

### PR DESCRIPTION
**Pull request by pangor**

### CODE REVIEW

**Comment by revolunet** [comment]
thanks for the PR !
could you please rebase ?

**Comment by pangor** [comment]
Sure, what do you the the feature thread  rebased into?

**Comment by pangor** [comment]
should I issue a new pull request after the rebase has been pushed to my fork's repository?

**Comment by revolunet** [comment]
No its automatic if you update your branch... Thank you!

**Comment by pangor** [comment]
There have been too many changes to the revolunet/JSbooks repository since I submitted this pull request.  I need to review and then resubmit it along with the rest that I have ready to submit; therefore, I have closed this request, in favor the the soon to be reworked version.

**Pull request closed without merging**
