### PR TITLE
Add Javascript Challenges book.

### PR DESCRIPTION
**Pull request by tcorral**

### CODE REVIEW

**Comment by revolunet** [comment]
is it free ?

**Comment by tcorral** [comment]
Sure. https://github.com/tcorral/javascript-challenges-book


2015-01-06 10:26 GMT+01:00 Julien Bouquillon <notifications@github.com>:

**Comment by revolunet** [comment]
Thanks.
Could you please link to this page instead and add a note to the Buy link in the README ?

**Comment by tcorral** [comment]
Done, could you check it?

2015-01-06 10:36 GMT+01:00 Julien Bouquillon <notifications@github.com>:

**Pull request merged**
