### PR TITLE
Update survivejs entry

### PR DESCRIPTION
**Pull request by bebraw**
Updated cover and description.

### CODE REVIEW

**Comment by bebraw** [comment]
Any luck with this? I know you are busy. Just curious. :smile:

**Comment by revolunet** [comment]
woops, missed that one sorry !

**Comment by bebraw** [comment]
Cool, thanks. Happy holidays!

**Comment by revolunet** [comment]
yeah happy holidays too man :) :christmas_tree: :gift: :fireworks:

**Pull request merged**
